runtime: nodejs12
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.9
  max_concurrent_requests: 30
  min_pending_latency: 1s
  max_pending_latency: 15s
  max_instances: 5
inbound_services:
- warmup
env_variables:
  DISABLE_LEGACY_METADATA_SERVER_ENDPOINTS: "true"

service: "rendertron"
